1) Где применяется SVD?

В рекомендательных системах, в сжатии матрицы без потерь, в аппроксимации матрицей меньшего ранга
    
2) Можно ли применить SVD для квадратичных матриц?

Да

3) Что описывают матрицы $U, S, V ?$
    $$A = U S V^T$$
    
$U$ - ортогональная матрица левых собственных векторов $AA^T$

$V$ - ортогональная матрица правых собственных векторов $A^TA$

$S$ - диагональна матрица сингулярных чисел $\sigma_{1} > \sigma_{2} > \dots > \sigma_{r}$

4) Какими свойствами обладает $U, S, V ?$
    $$A_{mxn} = U_{mxm}S_{mxn}V_{nxn}^T$$

5) Для чего может понадобиться усечение матрицы сингулярных чисел?

Для низкорангового приближения. Таким образом получается сохранить наибольшую часть информации, задействовав меньше памяти

In [17]:
import numpy as np

A = np.array([[1, -1, 30, -16],
              [1, 6, 8, -3],
              [1, 1, 1, -1],
              [0, 5, 7, -2]])

U, S, V = np.linalg.svd(A)
num_components = 1
print('U\n', U[:, :num_components])
print('\nS\n', S[:num_components])
print('\nV\n', V[:num_components, :])

U
 [[-0.94679109]
 [-0.24481854]
 [-0.03969757]
 [-0.20512097]]

S
 [35.83924895]

V
 [[-0.03435639 -0.04429285 -0.8883508   0.45573088]]


Усечение было произведено по первой компоненте, т. к. первая компонента вносит наибольший вклад

In [2]:
print(S)

[3.58392490e+01 7.98252206e+00 1.35187874e+00 1.76113408e-16]


In [16]:
A_new = np.matrix(U[:, :num_components]) * np.diag(S[:num_components]) * np.matrix(V[:num_components, :])
print('Исходная матрица\n', A)
print('\nПриближенная матрица\n', A_new)
print('\nНорма Фробениуса\n', np.linalg.norm(np.matrix(A) - A_new, ord='fro'))

Исходная матрица
 [[  1  -1  30 -16]
 [  1   6   8  -3]
 [  1   1   1  -1]
 [  0   5   7  -2]]

Приближенная матрица
 [[  1.16579069   1.50295755  30.14376955 -15.46398872]
 [  0.30144683   0.38863047   7.7944899   -3.99863407]
 [  0.0488799    0.06301681   1.26388416  -0.64838242]
 [  0.25256693   0.32561366   6.53060575  -3.35025165]]

Норма Фробениуса
 8.096186423027575
